version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb

  data-service:
    build: ./data-service
    env_file:
      - ./data-service/.env
    depends_on:
      - mongodb

  load-balancer:
    build: ./load-balancer
    ports:
      - '8080:80'
    depends_on:
      - auth-service
      - data-service
    networks:
      - backend

networks:
  backend:
